### ISSUE TITLE
resolve invalid ITIS taxa to their valid taxa

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#110]
Some species interaction data sources use taxon ids that have been marked as invalid by the taxonomy used. For instance, [KerpForest database](http://dx.doi.org/10.1371/journal.pone.0109356) uses an [ITIS taxon id 167353](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=167353) (_Scorpaenichthys marmoratus_  (Girard, 1854)) that has been marked as invalid. ITIS does provide a valid name associated with it, namely [_Scorpaenichthys marmoratus_ (Ayres, 1854)](http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=692068). 

Currently, the EOL taxon hierarchy API does not seem to support resolving "invalid" ITIS taxon ids  to their valid ones, meaning that the invalid names show up in the unresolved names list (see [taxonomic matching wiki](https://github.com/jhpoelen/eol-globi-data/wiki/Taxonomy-Matching)). 

Assuming that we'd like to follow invalid names to their valid replacements, we need to either (a) convince EOL to include invalid names in their meta taxonomy or (b) implement this behavior in GloBI's taxonomic matching engine using ITIS's web API, similar to the approach taken for [WoRMS] (http://marinespecies.org).

@jhammock @KatjaSchulz are you aware that "invalid" ITIS taxon ids are excluded from EOL's "meta" taxonomy? Is there any way to convince you to include invalid names and redirect to the valid one (if available)?

**Comment by jhammock** [comment]
Invalid names aren't available in the API? I'm very surprised. Is this for all the hierarchies you're using, Jorrit? You mentioned ITIS and WoRMS. WoRMS wasn't sending us their unaccepted names until very recently, so they couldn't have been available via EOL even a few months ago...

**Comment by jhammock** [comment]
Have you been using this service? http://eol.org/api/docs/hierarchy_entries  There's a synonyms parameter. Is that not working or does it slow things way down? Still, going forward it's more a question of ensuring the synonyms are available in the data dump Jeremy is preparing, yes?

**Comment by jhpoelen** [comment]
@jhammock You are fast!

Here's the sequence of requests:
lookup ITIS taxon id 167353 using ```http://eol.org/api/search_by_provider/1.0/167353.json?hierarchy_id=903``` yields response ```[]```

However, for ITIS taxon 180547 sea otter (_Enhydra lutris_), a "valid" ITIS taxon, a http get request for ```http://eol.org/api/search_by_provider/1.0/180547.json?hierarchy_id=903``` responds ```[{"eol_page_id":328583}]```

**Comment by jhammock** [comment]
Oh, I see. Of course, you start from an unaccepted name, and you can't go the other direction using search_by_provider?

I imagine using a query like [http://eol.org/api/search/1.0.json?q=Mustela+lutris] is less desirable, assuming you already at this point in the process have some way to know which name (according to ITIS, or WoRMS, or someone) you are dealing with, and can avoid some homonym issues by following that hierarchy entry to the taxon concept ID?

**Comment by jhpoelen** [comment]
Yep. The idea is that a taxon id is more desirable than a name string. If there's an id available in addition to a (human readable) name, the id is used to do the taxon matching. In the particular example, the common name ```cabezon``` was provided, along with it's ITIS id 167353. Using the common name to do taxon resolving is possible, but less desirable in my opinion, even if the taxon id is marked as invalid. The reason is that the taxon id provides access to a wealth of unambiguous, linked information, whereas the common name does not.

**Comment by jhammock** [comment]
I see. Yes, if that's what your providers are giving you, then there's only one way to go, and the best possible workaround requires an extra hit to the (ITIS) API and risks a homonym match back on EOL. Stand by...

**Comment by jhpoelen** [comment]
@jhammock I've implemented the suggested workaround. Please consider this issue an example of a eol taxon conciliation feature request: include the unaccepted ids and attempt to connect them to their accepted taxon when someone is using the unaccepted id. Thanks for the discussion, closing issue.

**Comment by JRice** [comment]
Hey guys, this sounded like a fairly straightforward task until I started looking into it. I'm going to get moderately technical here, but I think it's at a level that's understandable.

Here's the query we're using now:

```ruby
HierarchyEntry.
  joins(:taxon_concept).
  where(identifier: params[:id],
    hierarchy_id: params[:hierarchy_id],
    visibility_id: Visibility.visible.id,
    taxon_concepts: {published: true}).
  order("hierarchy_entries.published DESC")
```

...At first, I assumed the problem was either with the ```published: true``` bit, or with the ```visibility: visible``` bit, so I removed both of them to find out... However, when I did that in production using your IDs, like this:

```ruby
HierarchyEntry.where(identifier: "167353", hierarchy_id: 903)
```

...I still get NO results. It looks like we haven't stored that identifier in EOL.

Am I missing something, or is that actually the problem?  Or are these IDs made up and thus I wouldn't expect to find them?

*Regardless,* what we're proposing here is slightly problematic. Could we instead add an _option_ to the API... say, something like "include_unpublished", and then it could return results that are either invisible or unpublished? i.e.: with that option set, we would run this query:

```ruby
HierarchyEntry.
  where(identifier: params[:id],
    hierarchy_id: params[:hierarchy_id]).
  order("published DESC, visibility_id DESC")
```

...I hesitate to have it _always_ return unpublished/invisible results. We might even have _two_ additional params, one for published and one for visible, if that's more interesting/useful, but it sounds like it's not.

Also, at present the result doesn't _indicate_ in any way what's published/visible: should we add that? If so, we may have to make this a new "version" of the API (which is a PITA). :\

Thanks. Sorry for the delay in getting to this.

**Comment by HudaSoliman** [comment]
Hi All, 
Actually, we don't store the identifier of the invalid  ITIS record since it's stored just as a synonym not a hierarchy entry as in the page : (http://eol.org/pages/212214/names/synonyms )
We only store the identifier of the preferred synonym  in the hierarchy entry which makes the ITIS  invalid identifiers unavailable for us.
Thanks.

**Comment by jhammock** [comment]
Wow; speedy follow up, Huda! Thanks for investigating, guys. If we acquire other API users who want to want to use provider IDs (I can imagine ITIS or certainly WoRMS wanting to use their own if they make use of our services, for instance) they'll probably also want to include their unaccepted synonyms. Those tend to have full records at the partner site; "unaccepted" is just a tag. Is it practical to store provider IDs for these names also? I'm assuming the partners provide IDs the same for accepted and unaccepted names. (?) If it's too hard for right now, it would be great to have in the new API.

**Comment by jhammock** [comment]
I see @HudaSoliman has closed the JIRA ticket we started for this, so I'm guessing at the next deploy these names will be present in the database? Should we then expect them in the API and if so, is there a new parameter? Or is there potentially another JIRA task associated with this use case, which I should enter into JIRA? 

Thanks, Huda!

**Comment by HudaSoliman** [comment]
Hi @jhammock , 
Yes, the names will be present in the API by the next  deploy. And,  nothing is changed in the passed parameters .we changed the query in the backend to include the unaccepted names within the serach.
p.s Sorry for the late reply
Thanks.

**Comment by jhammock** [comment]
Thanks!!
