### ISSUE TITLE
[FEATURE] Add taxon_path_ids as default field

### ISSUE THREAD

**Issue by coding46** [jhpoelen/eol-globi-data#124]
Would be nice if 'taxon_path_ids' is a default return fields of the 'findCloseMatches' api call.

**Comment by BrianHayden** [comment]
Hey jorrit,

Mails have been bouncing back from your xs4all.nl mailbox, which is apparently full.

Nothing too serious just some comments on the niche stuff, collaborators, data etc

B


Dr. Brian Hayden

Science Manager
Stable Isotope in Nature Laboratory (SINLAB<http://www.unb.ca/research/institutes/cri/sinlab/>)

Canadian Rivers Institute
Department of Biology
University of New Brunswick
Fredericton, NB
E3B 5A3, Canada

Tel: +1 (506) 451-6892
Skype: brian.hayden.work
Twitter: @DrHaydo<https://twitter.com/DrHaydo>
Web: www.brianhayden.org<http://www.brianhayden.org/>

Social Media Editor for The FSBI, an International Society for Fish Biology, find us on Twitter @TheFSBI<https://twitter.com/TheFSBI> and Facebook https://www.facebook.com/TheFSBI

**Comment by coding46** [comment]
Reason:
- currently we choose the return fields by adding 'field=' parameters
- so it might happen that there is more than one parameter with the same name, which normally is treated as a single parameter
- this breaks certain libraries, as they expect distinct parameter names and merge those with identical ones

As I'm in need of this method with all those fields in it and the library I've chosen handles it the way described set it as default for the moment would be a quick fix.

**Comment by jhpoelen** [comment]
@BrianHayden am cleaning up my mailbox . . . thanks for letting me know - I'll delete the comment when it is done. How creative to use github to reach me!

@coding46 : thanks for sharing this idea . . . happy to make a change and I am not quite sure about the use case, since I don't expect double use of a single param name. Could you please provide an example?

**Comment by coding46** [comment]
@jhpoelen 
```
http://api.globalbioticinteractions.org/findCloseMatches?field=taxon_name&field=taxon_common_names&field=taxon_path_ids
```
Here we have three times the parameter name 'field' which usually gets reduced into a single one.

**Comment by jhpoelen** [comment]
Who does collapses the query param to a single value rather than turning them into an array (according to spec)? Is this a library that you are using? 

The parsers I know of turn the duplicate keys into an array. I guess this is not clearly outlined in a spec if I have to believe an answer posted here: http://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys .

Just for completeness, here's an working example url:
http://api.globalbioticinteractions.org/findCloseMatches?taxonName=Plantae&field=taxon_name&field=taxon_common_names&field=taxon_path_ids

**Comment by jhpoelen** [comment]
Added default field as suggested. Perhaps we can discuss the repeated query param some other time. . .

**Comment by jhpoelen** [comment]
E.g. http://api.globalbioticinteractions.org/findCloseMatches?taxonName=Plantae now includes field ```taxon_path_ids``` by default.
