### ISSUE TITLE
TTD data. Loose ends and more images?

### ISSUE THREAD

**Issue by seltmann** [jhpoelen/eol-globi-data#133]
Great the the interactions are now searchable from GloBI! And soon on EOL. Great to see and looking forward to exploring what can be done through rglobi.

One thing I noticed is that we have lots of images of plant bugs that you should have. I am assuming I can add URLs for the images in our next update?

Also, below is some follow up from the upload. I think I emailed this to you:

I am using these URI for our relations:
https://docs.google.com/spreadsheets/d/1GCChIIChXvf98oMFg7OKUznflZiSP_XLdI_6mm0IP2w/edit?usp=docslist_api

You are welcome to use the list to update the interacts with relationship now if you like, or wait until the next update. The archives will only be moved once. At present they are on a development server for idigbio review. I'll move them to the production (and stable) location when that review is complete.

I understand that GloBI provides only raw hypothesis of interactions. Is it filtered for EOL? We also try to provide only the raw data as many of the interactions are unpublished to science and we are in the process of evaluating them. In other words, it is not our objective to clean up the data regarding correct/incorrect information interactions because we do that using statistics in post processing. Not an issue for research, but just curious how it is handled for a consumer product like EOL.

**Comment by jhpoelen** [comment]
@seltmann Thanks for your notes. 

Adding images urls would be great (thumbnail and full?) . . . and we'll figure out a nice way to use them. Right now now the nimble discovery tools use taxon level images retrieved from (mostly) EOL. I'd say it would be extra supporting evidence to have images of the actual specimen / labels used to describe the interaction. 

I've added a first pass at the interaction mappings. Once the production archives are available, we can poke around and see if the mappings are working as expected.

EOL uses an aggregated archive that GloBI produces. This archive contains aggregated interactions by study - so if a specific study contains multiple interactions describing the same interactions (e.g. man (*Homo sapiens*) eats dog (*Canis familiaris*)), only a single entry is available in the aggregate archive. Also, in this aggregate, only interactions are included that contain names that matches against some external (meta-)taxonomy (e.g. ITIS, NCBI, EOL, WoRMS, ALA). However, GloBI allows for discovery of the "raw" interaction data on the specimen / observations / fact level . . . all GloBI exports / results are derived from that.

Please provide the production archives when they are available so that we can close this issue.

**Comment by jhpoelen** [comment]
Issue is related to https://github.com/jhpoelen/eol-globi-data/issues/126 .

**Comment by jhpoelen** [comment]
@seltmann just curious: are there any updates of TTD interaction dataset available? If you do, please feel free to update and created pull request for https://github.com/globalbioticinteractions/tri-trophic-thematic-collection-network/blob/master/globi.json and https://github.com/globalbioticinteractions/digital-bee-collections-network/blob/master/globi.json

**Comment by jhpoelen** [comment]
Closing issue: @seltmann has updated the existing archives (e.g. https://github.com/globalbioticinteractions/tri-trophic-thematic-collection-network and https://github.com/globalbioticinteractions/digital-bee-collections-network) and added a new one (https://github.com/globalbioticinteractions/plant-bug-planetary-biodiversity-inventory).

Please comment is this issue if there's still loose ends.
