### ISSUE TITLE
Wood, SA, Russell, R, Hanson, D, Williams, RJ, Dunne, JA. 2015. Effects of spatial scale of sampling on food web structure. Ecology and Evolution. doi:10.1002/ece3.1640

### ISSUE THREAD

**Issue by woodsp** [jhpoelen/eol-globi-data#159]
Hey Jorrit, here's a new data-source for you:

Wood, S.A., Russell, R., Hanson, D., Williams, R.J. and Dunne, J.A. (2015) Effects of spatial scale of sampling on food web structure. Ecology and Evolution. (http://dx.doi.org/10.1002/ece3.1640)

The food-web data are provided as an appendix and in DataDryad (http://dx.doi.org/10.5061/dryad.g1qr6).

**Comment by jhpoelen** [comment]
Hey Spencer,

Thanks for sharing! I hope we'll get it available through GloBI shortly, time permitting.

-jrorit

**Comment by jhpoelen** [comment]
Hey Spencer, I made some time to have a closer look at your food webs. Two questions:

1. You mention that the links are  "[...] based on 6712 feeding observations collected from 745 sources [...]". Do you have the reference available so that the foodweb links can be traced to their original source?
2. In the paper, you mention various locations on and around Sanak Island. Would you happen to have a shape file or similar available so that the foodwebs can expressed in the spatially explicit way? I really liked how Szoboszlai et al. 2015 (https://github.com/jhpoelen/eol-globi-data/issues/158) published their shapefiles along with the links.

Curious to hear your response.

-jorrit

**Comment by jhpoelen** [comment]
Wood et al. 2015 is now available through GloBI. Please re-open this issue if you find any issues. Thanks @woodsp for sharing!
