### ISSUE TITLE
 Resource Ecology and Ecosystem Modeling - Groundfish Diet Data

### ISSUE THREAD

**Issue by jebyrnes** [jhpoelen/eol-globi-data#216]
http://access.afsc.noaa.gov/REEM/WebDietData/DietDataIntro.php

**Comment by jhpoelen** [comment]
hey @jebyrnes - thanks for pointing out the NOAA REEM ground fish diet data.

The ground fish diet data should now be searchable through GloBI (see screenshots below).
Note that the REEM ground fish data set uses National Oceanic Data Centers (NODC) taxon codes. GloBI has added support for looking up NODC taxon codes v8 (for more info see [NODC Taxonomic Code Version 8.0 on CD-ROM](https://www.nodc.noaa.gov/General/CDR-detdesc/taxonomic-v8.html) and their associated ITIS taxonomic serial numbers. This allows to resolve predator/prey taxa by id, rather than by the provided predator and prey names. 

For a more detailed description on how the data was mapped into GloBI, please see https://github.com/globalbioticinteractions/noaa-reem/ . 

If you have any questions / suggestions, please let me know. 

-jorrit

![screen shot 2016-04-08 at 9 47 31 am](https://cloud.githubusercontent.com/assets/1084872/14391262/d5dd2622-fd6f-11e5-9804-7cd13f87a608.png)
![screen shot 2016-04-08 at 9 47 11 am](https://cloud.githubusercontent.com/assets/1084872/14391263/d5df556e-fd6f-11e5-87d3-0c2ebc71229c.png)
