### ISSUE TITLE
use accepted GBIF taxon whenever available

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#240]
Some GBIF ids provided by data source (e.g. iNaturalist) point to synonyms of an accepted taxon.

For instance, [inaturalist observation 981937](http://www.inaturalist.org/observations/981937) links to [GBIF:5405201](http://www.globalbioticinteractions.org/?sourceTaxon=GBIF%3A5405201&interactionType=interactsWith) points to http://www.gbif.org/species/5405201 _Olearia lyallii_ which has accepted taxon http://www.gbif.org/species/3096980 _Anaphalioides trinervis_ .

**Comment by jhpoelen** [comment]
@kueda just curious - what it your policy on synonym name usage?

**Comment by jhpoelen** [comment]
GloBI now traverses GBIF accepted taxon whenever available.

**Comment by kueda** [comment]
Like all taxonomy, synonymy is subjective. Our taxonomic policies are at www.inaturalist.org/pages/curator+guide#policies. Basically out taxonomy is manually curated, so sometimes it's out of date, and we try to follow certain authorities for certain groups in certain places, which will not always agree with some other arbitrary authority like GBIF. In this case, _Olearia lyallii_ is not out of date because it is accepted by our authority for NZ plants, so we accept it too: http://nzflora.landcareresearch.co.nz/default.aspx?selected=NameDetails&TabNum=0&NameId=3D071399-F447-4191-BA1F-95EC8159BA42.

**Comment by jhpoelen** [comment]
@kueda thanks for clarification - sounds like a suitable pragmatic approach to names. Is there a way for GloBI to select the taxon id that iNaturalist prefers for a specific taxon / observation. Happy to create an taxonomic integration with the nzflora taxonomy when suitable. From the json,  I couldn't find any ```preferred taxon``` or similar fields.

**Comment by kueda** [comment]
I'm pretty sure we include an iNat taxon ID in almost all of our observation responses. If you're not seeing something you want, please include the URL you're using to retrieve the information and an example of what you'd like to see there.
