### ISSUE TITLE
citability status not connected for this resource

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#277]
Hello! 

The resource is https://github.com/millerse/A-Host-parasite-Catalog-of-North-American-Tachinidae-Diptera- , owner @millerse 

It has a zenodo presence and a DOI, and was added to the GloBI zenodo community more than 24 hours ago, but the DOI does not show on the status list. Did we miss something? Thanks!

**Comment by jhpoelen** [comment]
I just checked on the GloBI server, and the @millerse Zenodo publications are being processed: the changes are being propagated. I think It would be nice to have more of a instant gratification, rather than have to wait a couple of days... I don't see any technical limitation for making this happen, just need to find the time to do it.

**Comment by jhammock** [comment]
Thanks! Good to know we have the procedure down. I'd call speedier gratification a "nice to have". It's not like anyone will go through this process very often. Except @millerse :)

**Comment by jhpoelen** [comment]
@millerse Very nice to see that you've enabled the travis-ci checks. With the checks enabled a noticed a potential GloBI for through https://travis-ci.org/millerse/Buprestidae-of-North-America . Also, the datasets you've published to zenodo now have linked on the status page (see included screenshot). 

@jhammock Please feel free to close this issue if you think it has been addressed.

![millersedois](https://cloud.githubusercontent.com/assets/1084872/22311645/46fc4ea8-e309-11e6-834f-c6a2a2b0d36a.png)

**Comment by millerse** [comment]
@jhpoelen I am so happy to see the DOI's populating the datasets.
