### ISSUE TITLE
eventDateUnixEpoch has extraneous digits

### ISSUE THREAD

**Issue by SriniAnandIUDS** [jhpoelen/eol-globi-data#287]
For the "eventDateUnixEpoch" attribute the understanding is that the following hold true:
10 digit values are the number of seconds since 1970-01-01
13 digit values are the number of milliseconds since 1970-01-01
Negative values represent dates prior to 1970-01-01
However, there are thousands of negative 14 digit values (e.g. -61178300000000) and a few 13 digit values that convert into dates in the future.

The attached CSV file shows examples of eventDateUnixEpoch values with different lengths and 1 reference citation for each. In many cases, there maybe many citations for each epoch value.

**Comment by jhpoelen** [comment]
@SriniAnandIUDS thanks for reporting this issue. Could you please point me to the CSV file?

**Comment by SriniAnandIUDS** [comment]
Here it is now,
Srini
[eventDateUnixEpoch inconsistencies.zip](https://github.com/jhpoelen/eol-globi-data/files/880324/eventDateUnixEpoch.inconsistencies.zip)

**Comment by jhpoelen** [comment]
@SriniAnandIUDS thanks for sharing your detailed record. I can confirm that the current eventDateUnixEpoch is the number of milliseconds since January 1, 1970, 00:00:00 GMT. 

The I've checked the sources of the records you shared, and I didn't notice any inconsistencies aside from ```15,-62230467600000,"Beal, F. E. L. 1918. Food habits of the swallows, a family of valuable native birds. U.S. Dept. Agric. Bull. 619."```. Note that some datasets happened near 1970 (e.g. 8,-3600000,"Arnell, W. B. 1971. Prey utilization by nesting Golden Eagles (Aquila chrysaetos) in central Utah. Master's Thesis. Brigham Young Univ. Provo, UT.",).

More on the records with 15 digits in timestamp in a bit.

**Comment by jhpoelen** [comment]
@SriniAnandIUDS with your detailed examples, I was able to reproduce and fix a parsing bug used in the ingestion of Hurlbert's Avian Diet Database (see https;//github.com/hurlbertlab/dietdatabase for project). This should prevent the odd 15 digit timestamps ```-62230467600000``` from reoccurring in the interaction database. Until the fix propagates in the next couple of dates, please ignore all eventDate values  ```-62230467600000```. Thanks!

PS This was to only unexpected eventDate I encountered. Please let me know if there's any other concerns you have.

**Comment by jhpoelen** [comment]
@SriniAnandIUDS please feel free to communicate this to your non-github following team members.
