### ISSUE TITLE
Not sure if I added my interactions?

### ISSUE THREAD

**Issue by nipomensis** [jhpoelen/eol-globi-data#324]
Hi I am new to this - I forked the repository and edited all items as the instructions detailed and then I pulled the request and it disappeared - Is it submitted to be added to globi?

**Comment by jhpoelen** [comment]
Hi!

It seems you created your repository successfully at https://github.com/nipomensis/template-dataset but then proceeded to edit the template repository. at https://github.com/globalbioticinteractions/template-dataset . 

Suggest to:

1. to avoid confusion, rename your repository at https://github.com/nipomensis/template-dataset to something like Lupinus-nipomensis . 
1. re-edit globi.json and interactions.tsv and README.md in your own repository at https://github.com/nipomensis/[new name]

Please let me know if you need help doing this . . . you are almost there!

**Comment by nipomensis** [comment]
Hi - I edited the file names - is that better? Is it complete now, if so
should I see it on globi within a few days?

**Comment by jhpoelen** [comment]
Hi @nipomensis - 

I noticed that you changed the name of your repository to https://github.com/nipomensis/lupinus-nipomensis-interactions-2017 . Nice!

Some more comments:

1. I also noticed that you made some changed in a branch ```https://github.com/nipomensis/lupinus-nipomensis-interactions-2017/tree/nipomensis-interactions``` instead of the ```master``` branch. Currently, GloBI only looks at the master branch of a repository, so if you'd like to make your updates known to GloBI, please make your changes in the master branch https://github.com/nipomensis/lupinus-nipomensis-interactions-2017/tree/master .
2. In the default repository format, GloBI expects a file ```interactions.tsv``` and a file ```globi.json```. The ```interactions.tsv``` file is expected to use the first row as a column headers. I noticed that in https://github.com/nipomensis/lupinus-nipomensis-interactions-2017/blob/nipomensis-interactions/Lupinusnipomensis2017interactions.tsv you changed the name of the file ( ```Lupinusnipomensis2017interactions.tsv``` instead of ```interactions.tsv```) and removed first header row:

```
ITIS:104419	Miridae Nymph	RO:0002622	visits flowers of	ITIS:516356	Lupinus nipomensis	GEONAMES:8105481	Phillips 66 Oil Refinery Mesa	35.038741	-120.579352	
ITIS:104736	Closterocoris amoenus	RO:0002618	visits leaves of	ITIS:516356	Lupinus nipomensis	GEONAMES:8105481	Phillips 66 Oil Refinery Mesa	35.038741	-120.579352	2017-04
```
instead of 
```
sourceTaxonId  sourceTaxonName ...
ITIS:104419	Miridae Nymph	RO:0002622	visits flowers of	ITIS:516356	Lupinus nipomensis	GEONAMES:8105481	Phillips 66 Oil Refinery Mesa	35.038741	-120.579352	
ITIS:104736	Closterocoris amoenus	RO:0002618	visits leaves of	ITIS:516356	Lupinus nipomensis	GEONAMES:8105481	Phillips 66 Oil Refinery Mesa	35.038741	-120.579352	2017-04
```

Hope this helps and please let me know when you'd like me to do another review!

**Comment by jhpoelen** [comment]
If you find the default format constraining, i'd be happy to share some alternate ways to make your data accessible.

**Comment by jhpoelen** [comment]
@nipomensis @seltmann to help things move along, I created a copy of your data with expected filenames and related formats, please see https://github.com/globalbioticinteractions/lupinus-nipomensis-interactions-2017 . 

Please review and clone the repository, so you can manage/curate it yourself.

**Comment by nipomensis** [comment]
Hi Jorrit,

Sorry about the delay, I have been very busy recently and I totally forgot
- thank you for taking care of it. I could not figure out to clone (sorry I
am really slow at picking up code) so I renamed the files in my
repository(?) and added the data headers to the interactions file. I can't
seem to find them anymore so maybe they merged? Let me know if it works now
when you get the chance.

Thanks

**Comment by jhpoelen** [comment]
hi @nipomensis - thanks for your message. I can imagine that github can be a bit confusing at times. The changes you made are on the pull request to the repository https://github.com/globalbioticinteractions/template-dataset instead of your own repository at https://github.com/nipomensis/lupinus-nipomensis-interactions-2017. 

I suggest the following;
1. delete your repository at https://github.com/nipomensis/lupinus-nipomensis-interactions-2017
2. accept the collaborator request I'll send in a minute (I'll send one to @seltmann also)
3. (optional) we can more the repository at https://github.com/globalbioticinteractions/lupinus-nipomensis-interactions-2017 to another account if needed.

@seltmann - excellent example of why we need symbiota-like environments to make it easier to manage interaction data.

**Comment by seltmann** [comment]
@jhpoelen exactly! This is an excellent use case and a very valuable dataset. We are working on the manuscript now.

@nipomensis Thank you for helping make the sharing of interaction data better.

**Comment by nipomensis** [comment]
Hi Jorrit,

I did the 2 suggestions you put out in the last email. Is everything good
now? Should it show up in globi eventually?

Thank you for all your help

**Comment by jhpoelen** [comment]
@nipomensis you are now an admin of https://github.com/globalbioticinteractions/lupinus-nipomensis-interactions-2017 just like @seltmann . This means that you have full control over the repository and the data in it.

Your interaction data should show up in GloBI in the next couple of days. 

Something to consider in the future - 

1. add occurrenceID or any other identifiers that help to associate your observations to collection management system or any other system (inaturalist observations?)
2. publish the repository to zenodo. Zenodo has github integration. For more information, see  https://github.com/jhpoelen/eol-globi-data/wiki/Dataset-Management#citability or search for "zenodo github integration" .

**Comment by nipomensis** [comment]
Hi Jorrit,

The data updated today on Globi - I was looking it over and it says there
is an interaction with gallus (domestic chicken) which I didn't put in - I
checked the data sheet and crtl F'd it but I did not find it anywhere in
the data so I was unsure of why it was showing up on GLOBI

**Comment by jhpoelen** [comment]
Glad the dataset showed up. I've opened a separate issue for your observations. Hoping to have a look at that sooner rather than later.

**Comment by jhpoelen** [comment]
See https://github.com/jhpoelen/eol-globi-data/issues/327 .
