### ISSUE TITLE
Need expert check of the database for lifestages of predators and prey

### ISSUE THREAD

**Issue by PierreOcean** [jhpoelen/eol-globi-data#378]
Hi,

The database needs an in-depth expert check. Many links are wrong, at least because the whole information hasn't been reported. It seems you do not include lifestages in your database which is crucial when you consider ontogenetic diet shift.
For instance, the data base reports that "sprat is feeding on cod" which is only true if you say that "sprat is feeding on the EGGS and LARVAE of cod".
If you check the reference cited with the link, it is even written in the title:
Koester, F.W. 1992. Predation by herring and sprat on **cod eggs and larvae** in the Bornholm Basin 

If you want to build a food web, you will essentially take this information into account and it has become a hassle to check all the information collected from Globi... which can be a lot of links.
Same happens with links someone reported from the DAPSTOM database. All the lifestages informations are missing and it is highly misleading.

One of the problem might come from the variety of ways people report such links (e.g. "Cod larvae", "Cod (larvae)" "Cod_larvae" or as extra columns in their own datasets). This variety exists in Globi.

If you add two extra columns lifestage_predator and lifestage_prey with already formatted info (e.g. "larvae", "egg", "juvenile", "adult"), people will have to stick to this format. Quick fix but still need a check.

**Comment by jhpoelen** [comment]
Hi @PierreOcean - Thanks for taking the time to share the importance of life stages in species interactions. 

I agree that life stage information is important to maintain. This is why GloBI has considered life stages from the beginning and included in the method paper at https://doi.org/10.1016/j.ecoinf.2014.08.005 . However, there's always improvements to be made. 

Here's the status quo: First, the life stage information is not currently exposed in the various web tools, but the information is available via various data products and the api. Second, GloBI currently has various ways to detect/include life stages from data source: by extracting from a name (e.g., Gadus morhua eggs) using https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-taxon-resolver/src/main/resources/org/eol/globi/taxon/life-stage-mapping.csv or including an already parsed out field from an existing source datasets (e.g., juv/adult of designations from Fishbase/Sealifebase ).  Also, in the template dataset at https://github.com/globalbioticinteractions/template-dataset and https://github.com/globalbioticinteractions/template-dataset/blob/master/interactions.tsv you'll find that two columns are dedicated to life stage: sourceLifeStageId and sourceLifeStageName . 

Actions I took just now:

1. opened an issue #379 describing a desire to include life stage history in the various web UI tools that help explore interactions. I hope we can use this issue to share ideas on how to expose the life stage information in our basic web UI discovery tools. 
2. Looked at your example of sprat eating cod and confirmed that the life stage history is available via the data download and various data archives (e.g., the tsv archive at https://globalbioticinteractions.org/data ). See https://www.globalbioticinteractions.org/?interactionType=eatenBy&sourceTaxon=Gadus%20morhua&targetTaxon=Sprattus%20sprattus and associated data download via https://api.globalbioticinteractions.org/interaction.csv?type=csv&limit=4096&interactionType=eatenBy&sourceTaxon=Gadus%20morhua&targetTaxon=Sprattus%20sprattus&includeObservations=true&field=source_taxon_id&field=source_taxon_name&field=source_taxon_path&field=source_taxon_path_ids&field=source_specimen_life_stage_id&field=source_specimen_life_stage&field=source_specimen_physiological_state_id&field=source_specimen_physiological_state&field=source_specimen_body_part_id&field=source_specimen_body_part&field=interaction_type&field=target_taxon_id&field=target_taxon_name&field=target_taxon_path&field=target_taxon_path_ids&field=target_specimen_life_stage_id&field=target_specimen_physiological_state&field=target_specimen_physiological_state_id&field=target_specimen_physiological_state&field=target_specimen_body_part_id&field=target_specimen_body_part&field=latitude&field=longitude&field=study_citation&field=study_url&field=study_source_citation . For convenience, I've attached a copy to this issue.
[lifestageSpratCod.csv.txt](https://github.com/jhpoelen/eol-globi-data/files/2530782/lifestageSpratCod.csv.txt)
3. Poked around a bit in the DAPSTOM dataset and found that the life stage extraction from descriptions like  ```CALANUS SPP (NAUPLII)``` was not successful due to some limitations of the life stage term matcher. I was able to reproduce this issue in a test and I've made some improvements like making the term matcher ignore case (e.g., Nauplii is the same as nauplii or NAUPLII), and remove non-letter characters like parenthesis. These changes should propagate within a couple of days.  Also see https://github.com/jhpoelen/eol-globi-data/commit/362fbb77743a2fcdf362aa6045ba8f35b4df9f3d#diff-86c655b41058c0607ce2eeb0f3d49909R379 . 

Thanks again for your feedback and I am curious to hear your take on my responses. Also, if you have more specific examples of wrong links, please do share. In addition, please let me know if you have any suggestions on how to organize expert reviews of GloBI data.

**Comment by jhpoelen** [comment]
Hey @PierreOcean thanks for your specific examples. These examples help me reproduce what you are seeing and (hopefully) figure out what is going on. 

You noticed that the lifestage and citation info are always NA  when using _get_interactions_by_taxa("Gadus morhua")_ . This is because rglobi returns taxon level interactions by default. Because the interactions are grouped by taxa, record level attributes like life stage and citations are not included. However, if you'd like to do record/observation level queries, include returnobservations=T in your request:

```R
get_interactions_by_taxa("Gadus morhua", returnobservations=T)
```
You noticed that _Sprattus sprattus_ does not appear when using _get_interactions_by_taxa("Gadus morhua"). This is likely because rglobi only returns the first 1024 rows by default and because _Gadus morhua_ is a well studied commercial fish (many of us like to eat our Atlantic cod!), many interactions have been recorded. To include more records, you can say:

```R
get_interactions_by_taxa("Gadus morhua", otherkeys = list(limit = 4096))
```

Now, by narrowing down our query to reflect the use case of sprats eating cod eggs:

```R
get_interactions_by_taxa("Gadus morhua", targettaxon="Sprattus sprattus", includeobservations=T, interactiontype="eatenBy", otherkeys = list(limit = 4096))
```
which, in my r console produced the result

 source_taxon_external_id | source_taxon_name | source_taxon_path | source_specimen_life_stage | interaction_type | target_taxon_external_id | target_taxon_name | target_taxon_path | target_specimen_life_stage | latitude | longitude | study_citation | study_source_citation 
 --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
EOL:206692 | Gadus morhua | Animalia \| Chordata \| Actinopterygii \| Gadiformes \| Gadidae \| Gadus \| Gadus morhua | eggs |  preyedUponBy  | EOL:607993 | Sprattus sprattus | Animalia \| Chordata \| Actinopterygii \| Clupeiformes \| Clupeidae \| Sprattus \| Sprattus sprattus | juv./adults |  NA | NA |  Koester, F.W. 1992. Predation by herring and sprat on cod eggs and larvae in the Bornholm Basin - preliminary results. ICES C.M./J:41. | Froese, R. and D. Pauly. Editors. 2016. FishBase. World Wide Web electronic publication. www.fishbase.org, version (10/2016). Accessed at <https://github.com/globalbioticinteractions/fishbase/archive/7e67537c10ab6def64e0e7aa7953af28f6198d2a.zip> on 24 Oct 2018.

Please let me know whether this addresses your concerns.
                                                                                                                                                                                                                                              
Also, I realize that there's definitely room for improvement on how to better explore existing species interaction datasets. I'd be curious to know whether you have any suggestions on how to make rglobi or GloBI's web tools a little better. Pull requests are definitely considered! rglobi lives at https://github.com/ropensci/rglobi and the web tools are embedded in https://github.com/globalbioticinteractions/globalbioticinteractions.github.io .

**Comment by jhpoelen** [comment]
Re: ICES stomach dataset. I reviewed the dataset and did not find any life stage information. Can you please point me to a data source that includes the life stage info? Are you referring to predator age? 

Here's some lines for the beginning of the ICES dataset - 


File Name | Latitude | Longitude | Estimated Lat/Lon | Date/Time | Year | Quarter | Month | Day | Time | Station/Haul | Sample Number | ICES StomachID | Depth | Temperature | Country | Ship | ICES Rectangle | Sampling Method | Predator | Predator NODC Code | Predator (mean) Lengh | Predator (mean) Weight | Predator (mean) Age | Predator Lower Length Bound | Predator Upper Length Bound | CPUE | Number Stomachs With Food | Number Stomachs Regurgitated | Number Stomachs With Skeletal Remains | Number Stomachs Empty | Number Stomachs | Digestion Stage | Prey Species Name | Prey NODC Code | Prey Weight | Prey Lower Length Bound | Prey Upper Length Bound | Prey Number | ICES Internal ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Exccoddatsto_815 | 55.25 | 8.5 | Yes | 01/01/1981 00:00:00 | 1981 | 1 | 1 | 1 |   |   | 26 | 26 |   |   |   |   | 39F8 | Demersal sampling | Gadus morhua | 8791030402 | 125 |   |   | 100 | 150 | 29 | 26 | 0 | 0 | 2 | 28 |   | Polychaeta | 5001000000 | 1.5 |   |   | 5 | 1
Exccoddatsto_815 | 55.25 | 8.5 | Yes | 01/01/1981 00:00:00 | 1981 | 1 | 1 | 1 |   |   | 26 | 26 |   |   |   |   | 39F8 | Demersal sampling | Gadus morhua | 8791030402 | 125 |   |   | 100 | 150 | 29 | 26 | 0 | 0 | 2 | 28 |   | Nereis | 5001240400 | 5.3 |   |   | 1 | 2

**Comment by PierreOcean** [comment]
Hi @jhpoelen 
I checked our code. We were not returning all observations and did not increase the rows limit.
I think it is a bit counter intuitive to not return the life stages when returning single interactions.
There should be an intermediate step/case to what exists now.

We currently can retrieve:

1. returnObservations = F
A eats B... ref1 (no duplicates, the diet of individuals is eliminated)
which retrieves a limited amount of data, basically one reference per row.

2. returnObservations = T
A1 of lifestage X eats B1 of lifestage Y... ref1 (duplicates of interactions, one row per individuals, 1 is the identifier of the individual)
which requires retrieving a huge chunk of data

There should be an intermediate case where life stages are not considered as duplicates:
A1 lifestage==NA eats B1 lifestage ==NA... ref1
A2 adult eats B2 NA...ref1
A3 juvenile eats B3 larvae...ref1
... etc
However you would only retrieve such interactions once so instead of retrieving 1 observation or thousands, you would retrieve at most 25 from each reference (if you consider every possible interactions between NA, adult, juvenile, larvae, eggs). That way you make sure to get all the information you need in the least amount of effort.

To me, it seems the fastest and easiest way to implement.
Our food web could contain 500 species so if we have to retrieve every single observations and deal with those, it takes edge (if our servers allows it) when we do not need to retrieve the 4,000 interactions for Cod eats Herring.

**Comment by jhpoelen** [comment]
@PierreOcean Just wanted to let you know that I did not forget about the topic around lifestages in GloBI and the datasets is help to provide access to. In fact, a similar data access issues came up in similar discussions (see https://github.com/ropensci/rglobi/issues/29 ). I'd be curious to hear your thoughts on that discussion. Thanks for being patient as I am trying to figure out how to parse and address the important issues that you shared.

**Comment by jhpoelen** [comment]
@PierreOcean thanks for being patient. I had a brief look at the lifestage values as retrieved from existing datasets via GloBI. I did the following:

1. download all the aggregated data via ```curl -L https://depot.globalbioticinteractions.org/snapshot/target/data/tsv/interactions.tsv.gz > interactions.tsv.gz``` 
2. combine the source/target life stage ids/terms using 
```
zcat interactions.tsv.gz | cut -f27,28 | tail -n+2 > lifestages.tsv
zcat interactions.tsv.gz | cut -f61,62 | tail -n+2 >> lifestages.tsv
```
3. make a list of all unique lifestage id/name pairs and counted 1524 unique id/name pairs
```
cat lifestages.tsv | sort | uniq > lifestages_unique.tsv
cat lifestages_unique.tsv | wc -l
``` 
4. check for the nauplii lifestages and found a typo ```naupliii``` along with the uberon term at (see also https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0014406) one:
```console
$ cat lifestages.tsv | sort | uniq | grep "naupli"
no:match	naupliii
UBERON:0014406	nauplius stage
```
5. found that that 1089329 out of 6907704 (~1 out of 7) source/target had life stages defined:
```
$cat lifestages.tsv | grep -v -P "\t$" | wc -l
1089329
$ cat lifestages.tsv | wc -l
6907704
```

Hopefully, with this, I've shown that (a) life stages are available via easy to parse csv/tsv archives at https://globalbioticinteractions.org/data  (b) life stages names vary widely in quality, consistency if they are defined at all (similar to taxonomic names) and (c) relatively few, only about 1500, unique life stage id/name pairs exist . 

Ideally, we'd have to opportunity to either contact the original datasource owner and help standardize terms, or map existing terms into more consistent ones using entries in
https://github.com/jhpoelen/eol-globi-data/blob/master/eol-globi-taxon-resolver/src/main/resources/org/eol/globi/taxon/life-stage-mapping.csv

@PierreOcean curious to hear your thoughts on all this, especially on how you'd like to engage the data set owners or other experts (such as yourself?) to help make the life stage terms a little more consistent.

**Comment by jhpoelen** [comment]
@PierreOcean Thanks again for your feedback. To summarize, your feedback concerned the importance of including lifestages of organisms when making species interaction claims. I very much agree and I hope that my detailed examples shows that GloBI does take the life-stage information into account when provided by the originating dataset. Resource and time permitting, I hope that life-stages will get a more prominent role in the basic exploratory web UIs that GloBI provides. Meanwhile, I hope that the life-stage information included in the data products available through https://globalbioticinteractions.org/data will suffice. If you feel that life-stage information available in source datasets are not properly indexed by GloBI, please open a separate issue  detailing the datasets and the expected and actual outcomes. Needless to say, please do holler if there's other concerns / ideas your have.
