### ISSUE TITLE
resolving eol page url for Bees (Apis, https://eol.org/pages/216713) results in status code 500, Internal server error 

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#383]
Resolving eol page url for Bees (Apis, https://eol.org/pages/216713) results in status code 500, Internal server error.

![screenshot from 2018-11-20 07-34-06](https://user-images.githubusercontent.com/1084872/48784136-e66db880-ec96-11e8-95fb-eaea0ffa40bc.png)

**Comment by jhpoelen** [comment]
Could you provide a complete list of the "some that got away from us" ? If not, could you provide a complete list of all supported taxon page id, ideally including their hierarchies, ids, common names etc?

**Comment by jhpoelen** [comment]
Also, I'd be curious to hear your thoughts on preventing this kind of [linkrot](https://en.wikipedia.org/wiki/Link_rot) for future version of EOL. I'd like to learn from this so that I can write integrations that take less effort to maintain.

**Comment by jhammock** [comment]
The [current version of the hierarchy](https://opendata.eol.org/dataset/tram-580-581/resource/bac4e11c-28ab-4038-9947-02d9f1b0329f) lists matched v2 IDs in the taxa file, under EOLid, where available. 

In the next version of EOL we should be able to migrate taxa in directly rather than reharvest them, so taxon IDs should survive, but I can still imagine linkrot being a problem for media in a future migration. The media files were never meant to be stable. My generic advice for use of media is to either access them starting from a taxon level query or cache them.

That being said, the Common name + thumbnail use case is a common one, and if it was the bulk download implementation of that which tripped you up, I'm open to ideas for a sustainable solution for people who prefer not to (or whom we prefer not to) rely on the api...

**Comment by jhpoelen** [comment]
@jhammock thanks for sharing. For now, I've disabled the eol links and am very excited to start using the published hierarchy instead. Just curious: does the link always point to the most recent?

**Comment by jhammock** [comment]
we will have a stable link to the current version pretty soon, but I can't yet guarantee it'll be this one. We'll put it in the description when we get that organized.

**Comment by jhpoelen** [comment]
Thanks for sharing. I'll hold off on supporting an archive based integration with EOL (see https://github.com/globalbioticinteractions/nomer/issues/11) until the dust settles.

@jhammock Just curious: can you guarantee that https://opendata.eol.org/dataset/tram-580-581/resource/bac4e11c-28ab-4038-9947-02d9f1b0329f will stick around? If not, I'd suggest to create some Zenodo publication. If you can't do that, please let me know and I'll do it myself.  

The original url with the deprecated EOL id is no longer created by GloBI per https://github.com/jhpoelen/eol-globi-data/issues/384 . This is why I am closing this issue.

**Comment by jhammock** [comment]
Katja wants to formalize the next version of the DH. Zenodo seems likely; I don't think we have a better option right now

**Comment by jhpoelen** [comment]
@jhammock great to hear that there's another version of the EOL taxon hierarchy is in the works. Are you planning to keep the current version around?

**Comment by jhammock** [comment]
I expect Katja wants to keep the version history, if only for her own sanity. The versions up until now will probably stay right where they are.

**Comment by jhpoelen** [comment]
related to #403
