### ISSUE TITLE
assorted parasites of starfish & kin

### ISSUE THREAD

**Issue by jhammock** [jhpoelen/eol-globi-data#69]
also small, most species pairs are in tables, others scattered through the docs (OCR text) 

http://www.int-res.com/articles/dao/2/d002p147.pdf
http://www.int-res.com/articles/dao/2/d002p205.pdf

I will now stop stumbling over marine parasites.

**Comment by millerse** [comment]
Hey Jorrit, @jhpoelen here is one of those articles that Jen @jhammock posted above: https://github.com/millerse/Diseases-of-Echinodermata.-I./tree/master

**Comment by jhpoelen** [comment]
@millerse Wow - you are fast! 

Couple of comments:

 1. to ensure inclusion in GloBI (and EOL), please fork a repository from http://github.com/globalbioticinteractions/template-dataset and update the globi.json, data files, repository name and README,md with appropriate info. 
 2. In line 30 of interactions.tsv, you mentioned ```Bald-sea-urchin disease``` and ```parasite of```. Assuming that this is a pathogen, I suggest using the scientific / latin name for the pathogen (perhaps _Listonella anguillarum_ or _Aeromonas salmonicida_?). Also suggest to use the interaction type ```pathogen of``` with id ```RO:0002556```.
 3. rather than including a separate locality file, I'd recommend to expand these into the interactions.tsv file with a new line for each locality. Ideally, a centroid lat/lng pair would accompany the locality to make it easy to point to an (approximate) place on the map. Perhaps http://geonames.org can help you look up these coordinates.

Thanks for your contribution and for being patient with me!

Let me know if you have any questions / comments.

-jorrit

**Comment by millerse** [comment]
Will do!

**Comment by jhpoelen** [comment]
Great! One more thing . . . if possibly try to reuse the geonames ids for locality ids. This way, we can point to an existing definition.

Example:
Barents Sea is available at http://www.geonames.org/630674/barents-sea.html, where the geonames locale id is 630674 and the (English) locale name is Barents Sea. Also, you can see that decimalLatitude and decimalLongitude is (lat,lng) (74, 36). In the interactions.tsv file just prefix the geonames id with GEONAMES: . In this case it would be GEONAMES:630674 .

Thanks!

**Comment by cmungall** [comment]
It seems two distinct taxa may be responsible:

https://en.wikipedia.org/wiki/Bald_sea_urchin_disease

I don't know if it's valid to swap out the disease row for two rows with each taxon (probably not - different parasites may be responsible in different locales)

How about having different kinds of triples (sorry if I'm complicating things..)

 1. tax-[interacts with]->tax (with relation coming from biotic interaction branch of RO)
 2. disease-[caused by]->tax (we have triples like this in DO already)
 3. tax-[infected by]->disease

But to avoid loss it may be necessary to combine 2 and 3 in one statement (e.g. paraside infects host causing disease)

**Comment by cmungall** [comment]
I don't know if this helps but I have considered before auto-generating an invertebrate disease ontology from https://en.wikipedia.org/wiki/Category:Animal_diseases

**Comment by jhpoelen** [comment]
@millerse does the source material mention which taxon caused the cases of ```Bald-sea-urchin disease``` reported at specific location? If so, I suggest to use the taxa instead with ```pathogen of ``` interaction type. If not, I'd suggest to leave the name as is, and revisit as soon as we have a good way to encode this.

@cmungall could you please provide an example is a separate archive on how to encode this situation. This might actually also address #109 . 

I hope this makes sense if not, please propose alternate approach . . . 

-jorrit

**Comment by millerse** [comment]
@jhpoelen The source material does not mention which taxon causes Bald-sea-urchin disease.  I suppose I should just use the Bald-sea-urchin disease in the taxon field.

**Comment by jhpoelen** [comment]
Sounds good! Thanks for checking.

**Comment by jhpoelen** [comment]
@millerse you contributions made are now available through GloBI. Thanks for helping make this interaction data available! Please re-open this issue if you have concerns / issues.

from http://globalbioticinteractions.org/references.html 

![screen shot 2015-02-13 at 12 40 39 pm](https://cloud.githubusercontent.com/assets/1084872/6194918/e0d9b668-b37d-11e4-8b0d-1de63b6629ee.png)
