### ISSUE TITLE
add new darwin core export with taxon roll-up to taxon rank of order.

### ISSUE THREAD

**Issue by jhpoelen** [jhpoelen/eol-globi-data#79]
as discussed with @jhammock @JRice

Currently, GloBI produces two darwin core archives. One with all interaction observations and other with distinct interaction observations aggregated by study. 

In the future, we'd like to introduce an additional one. This darwin core archive expands the interaction observations for lower order taxa up to the taxon rank of order. This would make it easier for GloBI data consumers like http://eol.org to get an overview of interaction summaries of higher order taxonomic ranks. 

For instance, if a sea otter (_Enhydra lutris_) is observed eating a red rock crab (_Cancer productus_), then the otter's higher order taxa Enhydra, Mustelidae etc will also be associated to that same interaction with the red rock crab. 

This taxon interaction roll-up will happen up-until the ```order``` rank. Also the number of inferred interactions will be limited to 15,000 per higher order taxonomic rank.

**Comment by jhpoelen** [comment]
@jhammock just produced first pass at a darwin core archive with inferred interactions between taxa up to taxonomic rank ```order```. You can find an archive [here](https://globi.s3.amazonaws.com/snapshot/target/eol-globi-datasets-1.0-SNAPSHOT-darwin-core-aggregated-roll-up.zip).

with the current implementation, all permutations between taxonomic ranks are used to infer interactions. For instance, if an interaction between specimen with (sub)species level classification are recorded, this will amount about 4 * 5 = 20 interactions. For example, man (_Homo sapiens_) eating dog (_Canis lupus familiaris_), will expand to:

source | type | target 
 --- | --- | ---
_Homo sapiens_ | ate | _Canis lupus familiaris_
Homo | ate | _Canis lupus famliaris_
Hominidae | ate | _Canis lupus familiaris_
Primates | ate | _Canis lupus familiaris_
_Homo sapiens_ | ate | _Canis lupus_
_Homo sapiens_ | ate | Canis
_Homo sapiens_ | ate |  Canidae
_Homo sapiens_ | ate |  Carnivora
... | ... | ...

Please confirm that this is the desired behavior.

The most recent archive with rolled-up taxa aggregated by study and interaction type, this amounts to about 2.3M associations (i.e. interactions) between about 81k taxa (of any rank). The (compressed) archive is about 50MB, while the uncompressed archive contains about 1.2GB (!). This is about 5x the currently used archive (w/ study interaction type aggregation).

I noticed that the meta data format used does not pass the GBIF archive validator. What is EOLs policy on darwin core archive validation?

Looking forward to your feedback!

**Comment by cmungall** [comment]
If space is an issue, then instead of `N* × M*`, what about `N* × M ∪ N × M*`? i.e. 4+5 rather than 4*5 tuples in this case.

i.e. you wouldn't have `Primates ate Canidae`

Advantages: queries of the form "what interacts with X" (where X can be higher level taxa like primates or canids) could be directly supported using pre-inferred assertions.

Disadvantages: queries of the form "does X interact with Y" cannot be directly calculated without taxonomic inference. 

Either way, presumably after the query is performed you only want to report the most specific. E.g. if I query for Primates, I want the answer "Homo sapiens ate Canis lupus familiaris"; I'm not sure if it's possible to have a 5-tuple in DC (e.g. N*,ate,M*,N,M)

Caveat: I don't know much about darwin core or about the requirements for this ticket or the technical environment in which it's implemented so ignore if not relevant!

**Comment by jhpoelen** [comment]
@cmungall thanks for your suggestion. As far as I am concerned size is not an issue: the compressed archives are pretty manageable. Also, the expansion occurs during the darwin core export: the internal graph model does not contain explicit taxon expansion yet.

@jhammock is a 5x increase in size compared to existing archive an issue for the EOL ingestion pipeline?

**Comment by jhammock** [comment]
Excellent :) Jorrit's description at the top of the thread sounds like expected behaviour. We are agnostic to GBIF's validator but our own is a good predictor of success: http://services.eol.org/dwc_validator/

5x the current GloBI resource file is emphatically not a problem. I also haven't heard of DwCA taking lists of occurrences, though EOL may someday have ambitions to do that onsite. We have a similar mechanism in place for selected "regular" data (non-associations) but it's fairly limited. (only affects what shows on taxon pages.)

My only immediate concern is that the archive file linked above has a nice meta file, but all the other files are empty...

**Comment by jhpoelen** [comment]
@jhammock Thanks for chiming in. Also, thanks for letting me know about the empty archives. This was a mistake and they should be available in about 5 mins. Sorry for the inconvenience.

**Comment by jhpoelen** [comment]
EOL now includes the roll-up archive. A short sanity check confirmed that the roll-up data is included as requested: [True Seals (Phocidae) family taxon page](http://eol.org/pages/7666/overview) and [Carnivora order taxon page](http://eol.org/pages/7662/overview) now include a wealth of species interaction data. However, the page for [Mammalia class taxon page](http://eol.org/pages/1642/overview) does not, as specified. 

@jhammock Please re-open this issue if you have any change suggestions.
